# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.cache/wt [current_project]
set_property parent.project_path /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
add_files /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/design_1_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
read_xdc /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/constrs_1/imports/Labs/Zedboard_Master.xdc
set_property used_in_implementation false [get_files /home/physics/Labs/week17/week17_20190306_project4_microblazeHW/week17_20190306_project4_microblazeHW.srcs/constrs_1/imports/Labs/Zedboard_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
