# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/physics/Labs/week17/week17_20190305_project3_XADCtoLEDS/week17_20190305_project3_XADCtoLEDS.cache/wt [current_project]
set_property parent.project_path /home/physics/Labs/week17/week17_20190305_project3_XADCtoLEDS/week17_20190305_project3_XADCtoLEDS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
add_files -quiet /home/physics/Labs/week17/week17_20190305_project3_XADCtoLEDS/week17_20190305_project3_XADCtoLEDS.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp
set_property used_in_implementation false [get_files /home/physics/Labs/week17/week17_20190305_project3_XADCtoLEDS/week17_20190305_project3_XADCtoLEDS.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp]
read_vhdl -library xil_defaultlib /home/physics/Labs/week17/week17_20190305_project3_XADCtoLEDS/week17_20190305_project3_XADCtoLEDS.srcs/sources_1/new/XADCtoLEDs.vhd
read_xdc /home/physics/Labs/week17/week17_20190305_project3_XADCtoLEDS/week17_20190305_project3_XADCtoLEDS.srcs/constrs_1/imports/Labs/Zedboard_Master.xdc
set_property used_in_implementation false [get_files /home/physics/Labs/week17/week17_20190305_project3_XADCtoLEDS/week17_20190305_project3_XADCtoLEDS.srcs/constrs_1/imports/Labs/Zedboard_Master.xdc]

synth_design -top XADCtoLEDs -part xc7z020clg484-1
write_checkpoint -noxdef XADCtoLEDs.dcp
catch { report_utilization -file XADCtoLEDs_utilization_synth.rpt -pb XADCtoLEDs_utilization_synth.pb }
