# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/physics/Labs/week17/week17_20190305_project2_ledsw/week17_20190305_project2_ledsw.cache/wt [current_project]
set_property parent.project_path /home/physics/Labs/week17/week17_20190305_project2_ledsw/week17_20190305_project2_ledsw.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
read_vhdl -library xil_defaultlib /home/physics/Labs/week17/week17_20190305_project2_ledsw/week17_20190305_project2_ledsw.srcs/sources_1/new/ledsw.vhd
read_xdc /home/physics/Labs/week17/week17_20190305_project2_ledsw/week17_20190305_project2_ledsw.srcs/constrs_1/imports/Labs/Zedboard_Master.xdc
set_property used_in_implementation false [get_files /home/physics/Labs/week17/week17_20190305_project2_ledsw/week17_20190305_project2_ledsw.srcs/constrs_1/imports/Labs/Zedboard_Master.xdc]

synth_design -top ledsw -part xc7z020clg484-1
write_checkpoint -noxdef ledsw.dcp
catch { report_utilization -file ledsw_utilization_synth.rpt -pb ledsw_utilization_synth.pb }
