# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/physics/Labs/week4/week4_20181016_project2_blockdesign/week4_20181016_project2_blockdesign.cache/wt [current_project]
set_property parent.project_path /home/physics/Labs/week4/week4_20181016_project2_blockdesign/week4_20181016_project2_blockdesign.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /home/physics/Labs/Vivado_IP/sixteen_bit_to_display [current_project]
add_files /home/physics/Labs/week4/week4_20181016_project2_blockdesign/week4_20181016_project2_blockdesign.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/physics/Labs/week4/week4_20181016_project2_blockdesign/week4_20181016_project2_blockdesign.srcs/sources_1/ipshared/user.org/sevbittwo_v1_0/a896de47/src/Basys3_Master.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week4/week4_20181016_project2_blockdesign/week4_20181016_project2_blockdesign.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/physics/Labs/week4/week4_20181016_project2_blockdesign/week4_20181016_project2_blockdesign.srcs/sources_1/bd/design_1/design_1.bd]

read_vhdl -library xil_defaultlib /home/physics/Labs/week4/week4_20181016_project2_blockdesign/week4_20181016_project2_blockdesign.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
read_xdc /home/physics/Labs/week4/week4_20181016_project2_blockdesign/week4_20181016_project2_blockdesign.srcs/constrs_1/imports/Labs/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/physics/Labs/week4/week4_20181016_project2_blockdesign/week4_20181016_project2_blockdesign.srcs/constrs_1/imports/Labs/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
