# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/physics/Labs/week5/week5_20181023_project1c_unsignedxadc/week5_20181023_project1c_unsignedxadc.cache/wt [current_project]
set_property parent.project_path /home/physics/Labs/week5/week5_20181023_project1c_unsignedxadc/week5_20181023_project1c_unsignedxadc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /home/physics/Labs/Vivado_IP/unsignedPotDiv [current_project]
add_files -quiet /home/physics/Labs/week5/week5_20181023_project1c_unsignedxadc/week5_20181023_project1c_unsignedxadc.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp
set_property used_in_implementation false [get_files /home/physics/Labs/week5/week5_20181023_project1c_unsignedxadc/week5_20181023_project1c_unsignedxadc.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp]
read_vhdl -library xil_defaultlib /home/physics/Labs/week5/week5_20181023_project1c_unsignedxadc/week5_20181023_project1c_unsignedxadc.srcs/sources_1/imports/new/potdiv.vhd
read_xdc /home/physics/Labs/week5/week5_20181023_project1c_unsignedxadc/week5_20181023_project1c_unsignedxadc.srcs/constrs_1/imports/Labs/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/physics/Labs/week5/week5_20181023_project1c_unsignedxadc/week5_20181023_project1c_unsignedxadc.srcs/constrs_1/imports/Labs/Basys3_Master.xdc]

synth_design -top potdiv -part xc7a35tcpg236-1
write_checkpoint -noxdef potdiv.dcp
catch { report_utilization -file potdiv_utilization_synth.rpt -pb potdiv_utilization_synth.pb }
