webtalk_init -webtalk_dir /home/physics/Labs/week13/Stuff That DIdnt Work/20190205_week13_project1a_microblazeat2/20190205_week13_project1a_microblazeat2.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 12 16:30:34 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1215546" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "200191577_1777487703_0_828" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "20ec9e34-b664-4764-b60a-f6edf65e00bf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "28f5ed6e-1d8e-432d-b58e-87957385a4b3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3393.681 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_transmit -clientid 307777862 -regid "200191577_1777487703_0_828" -xml /home/physics/Labs/week13/Stuff That DIdnt Work/20190205_week13_project1a_microblazeat2/20190205_week13_project1a_microblazeat2.hw/webtalk/usage_statistics_ext_labtool.xml -html /home/physics/Labs/week13/Stuff That DIdnt Work/20190205_week13_project1a_microblazeat2/20190205_week13_project1a_microblazeat2.hw/webtalk/usage_statistics_ext_labtool.html -wdm /home/physics/Labs/week13/Stuff That DIdnt Work/20190205_week13_project1a_microblazeat2/20190205_week13_project1a_microblazeat2.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
