# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Labs/Basys3_Master.xdc

# Block Designs: bd/passthrough1/passthrough1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==passthrough1 || ORIG_REF_NAME==passthrough1}]

# IP: bd/passthrough1/ip/passthrough1_xadc_block_0_0/passthrough1_xadc_block_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==passthrough1_xadc_block_0_0 || ORIG_REF_NAME==passthrough1_xadc_block_0_0}]

# IP: bd/passthrough1/ip/passthrough1_xadc_block_0_0/src/xadc_wiz_0/xadc_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0}]

# IP: bd/passthrough1/ip/passthrough1_DAC_0_0/passthrough1_DAC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==passthrough1_DAC_0_0 || ORIG_REF_NAME==passthrough1_DAC_0_0}]

# IP: bd/passthrough1/ip/passthrough1_clk_wiz_0_0/passthrough1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==passthrough1_clk_wiz_0_0 || ORIG_REF_NAME==passthrough1_clk_wiz_0_0}]

# XDC: ipshared/user.org/xadc_block_v1_0/836f3f48/src/Basys3_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==passthrough1_xadc_block_0_0 || ORIG_REF_NAME==passthrough1_xadc_block_0_0}] {/U0 }]/U0 ]]

# XDC: bd/passthrough1/ip/passthrough1_xadc_block_0_0/src/xadc_wiz_0/xadc_wiz_0_ooc.xdc

# XDC: bd/passthrough1/ip/passthrough1_xadc_block_0_0/src/xadc_wiz_0/xadc_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0}] {/U0 }]/U0 ]]

# XDC: ipshared/user.org/dac_v1_0/361bfde4/src/Basys3_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==passthrough1_DAC_0_0 || ORIG_REF_NAME==passthrough1_DAC_0_0}] {/U0 }]/U0 ]]

# XDC: bd/passthrough1/ip/passthrough1_clk_wiz_0_0/passthrough1_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==passthrough1_clk_wiz_0_0 || ORIG_REF_NAME==passthrough1_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/passthrough1/ip/passthrough1_clk_wiz_0_0/passthrough1_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==passthrough1_clk_wiz_0_0 || ORIG_REF_NAME==passthrough1_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/passthrough1/ip/passthrough1_clk_wiz_0_0/passthrough1_clk_wiz_0_0_ooc.xdc

# XDC: bd/passthrough1/passthrough1_ooc.xdc
