# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.cache/wt [current_project]
set_property parent.project_path /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_repo_paths {{/home/physics/Labs/week22/External IPs}} [current_project]
add_files /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/sources_1/bd/passthrough1/passthrough1.bd
set_property used_in_implementation false [get_files -all /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/sources_1/ipshared/user.org/xadc_block_v1_0/836f3f48/src/Basys3_Master.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/sources_1/bd/passthrough1/ip/passthrough1_xadc_block_0_0/src/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/sources_1/bd/passthrough1/ip/passthrough1_xadc_block_0_0/src/xadc_wiz_0/xadc_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/sources_1/ipshared/user.org/dac_v1_0/361bfde4/src/Basys3_Master.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/sources_1/bd/passthrough1/ip/passthrough1_clk_wiz_0_0/passthrough1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/sources_1/bd/passthrough1/ip/passthrough1_clk_wiz_0_0/passthrough1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/sources_1/bd/passthrough1/ip/passthrough1_clk_wiz_0_0/passthrough1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/sources_1/bd/passthrough1/passthrough1_ooc.xdc]
set_property is_locked true [get_files /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/sources_1/bd/passthrough1/passthrough1.bd]

read_vhdl -library xil_defaultlib /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/sources_1/bd/passthrough1/hdl/passthrough1_wrapper.vhd
read_xdc /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/constrs_1/imports/Labs/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/physics/Labs/week22/20190430_project2_passthroughdiag/20190430_project2_passthroughdiag.srcs/constrs_1/imports/Labs/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top passthrough1_wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef passthrough1_wrapper.dcp
catch { report_utilization -file passthrough1_wrapper_utilization_synth.rpt -pb passthrough1_wrapper_utilization_synth.pb }
