# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/physics/Labs/week16/week16_20180226_project1_horowitzalg/week16_20180226_project1_horowitzalg.cache/wt [current_project]
set_property parent.project_path /home/physics/Labs/week16/week16_20180226_project1_horowitzalg/week16_20180226_project1_horowitzalg.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
read_vhdl -library xil_defaultlib /home/physics/Labs/week16/week16_20180226_project1_horowitzalg/week16_20180226_project1_horowitzalg.srcs/sources_1/new/horowitz.vhd
read_xdc /home/physics/Labs/week16/week16_20180226_project1_horowitzalg/week16_20180226_project1_horowitzalg.srcs/constrs_1/imports/Labs/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/physics/Labs/week16/week16_20180226_project1_horowitzalg/week16_20180226_project1_horowitzalg.srcs/constrs_1/imports/Labs/Basys3_Master.xdc]

synth_design -top horowitz -part xc7a35tcpg236-1
write_checkpoint -noxdef horowitz.dcp
catch { report_utilization -file horowitz_utilization_synth.rpt -pb horowitz_utilization_synth.pb }
