# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/physics/Labs/week11/week11_20181211_project2_rednoserain/week11_20181211_project2_rednoserain.cache/wt [current_project]
set_property parent.project_path /home/physics/Labs/week11/week11_20181211_project2_rednoserain/week11_20181211_project2_rednoserain.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib /home/physics/Labs/week11/week11_20181211_project2_rednoserain/week11_20181211_project2_rednoserain.srcs/sources_1/imports/new/crystnotes.vhd
read_xdc /home/physics/Labs/week11/week11_20181211_project2_rednoserain/week11_20181211_project2_rednoserain.srcs/constrs_1/imports/Labs/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/physics/Labs/week11/week11_20181211_project2_rednoserain/week11_20181211_project2_rednoserain.srcs/constrs_1/imports/Labs/Basys3_Master.xdc]

synth_design -top raindeer -part xc7a35tcpg236-1
write_checkpoint -noxdef raindeer.dcp
catch { report_utilization -file raindeer_utilization_synth.rpt -pb raindeer_utilization_synth.pb }
