# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/physics/Labs/week19/week19_20190319_project2_xadctodac/week19_20190319_project2_xadctodac.cache/wt [current_project]
set_property parent.project_path /home/physics/Labs/week19/week19_20190319_project2_xadctodac/week19_20190319_project2_xadctodac.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
add_files -quiet /home/physics/Labs/week19/week19_20190319_project2_xadctodac/week19_20190319_project2_xadctodac.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp
set_property used_in_implementation false [get_files /home/physics/Labs/week19/week19_20190319_project2_xadctodac/week19_20190319_project2_xadctodac.runs/xadc_wiz_0_synth_1/xadc_wiz_0.dcp]
read_vhdl -library xil_defaultlib /home/physics/Labs/week19/week19_20190319_project2_xadctodac/week19_20190319_project2_xadctodac.srcs/sources_1/new/xadctodac.vhd
read_xdc /home/physics/Labs/week19/week19_20190319_project2_xadctodac/week19_20190319_project2_xadctodac.srcs/constrs_1/imports/Labs/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/physics/Labs/week19/week19_20190319_project2_xadctodac/week19_20190319_project2_xadctodac.srcs/constrs_1/imports/Labs/Basys3_Master.xdc]

synth_design -top xadctodac -part xc7a35tcpg236-1
write_checkpoint -noxdef xadctodac.dcp
catch { report_utilization -file xadctodac_utilization_synth.rpt -pb xadctodac_utilization_synth.pb }
